server:
  port: 8085
resilience4j:
  retry:
    instances:
      callServiceBRetry:
        max-attempts: 5
        wait-duration: 5s
        #enable-exponential-backoff: true
        #exponential-backoff-multiplier: 2
