server:
  port: 8085
resilience4j:
  retry:
    instances:
      callServiceBRetry:
        max-attempts: 5
        wait-duration: 2s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
      callServiceCThrowingException:
        maxAttempts: 3
        waitDuration: 2s
        retryExceptions:
          - java.lang.Exception
      callServiceDPredicate:
        maxRetryAttempts: 3
        waitDuration: 3s
        resultPredicate: com.example.resilientApi.predicates.ConditionalRetryPredicate
